name: List Repos
on: [workflow_dispatch]
jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - run: curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user/repos?per_page=100
